"Home",
"Enquiry", 
"Patient Enquiry", 
"Doctor Enquiry", 
"Patient Enquiry Details", 
"Admission Discharge And Transfer", 
"Patient Registration", 
"Patient Registration", 
"Update Patient Registration", 
"Patient Visit", 
"Patient Visit Search", 
"Patient Visit Details", 
"IP Admission", 
"IP Admission Search", 
"IP Admission Details", 
"IP Admission Transfer", 
"IP Admission Transfer Search", 
"IP Admission Transfer Details", 
"IP Admission Discharge", 
"IP Admission Discharge Search", 
"IP Admission Discharge Details", 
"Expiry Details", 
"Final Discharge", 
"Daily Bed Status", 
"OP MLC Case", 
"Appointment", 
"Appointment Setup", 
"Patient Appointments", 
"Investigation Appointments Setup", 
"Investigation Appointments", 
"Cancel Patient Appointments", 
"Cancel Investigation Appointments", 
"Out Patient Department", 
"OPD Waiting List", 
"OPD Cardiology", 
"OPD ENT", 
"OPD Onco Surgery Case Sheet", 
"OPD Ophthalmology", 
"Ophthalmology Follow Up", 
"Retinal Laser Proforma", 
"OPD Pediatric Case Sheet", 
"OPD Urology Case Sheet", 
"OPD -Main (AFMSF-7A 2002)  View ", 
"OPD- Main (AFMSF- 7A 2002)", 
"In Patient Surgery Requisition Form", 
"OPD Patient Info", 
"OPD Search Patient Previous Visit", 
"OPD Patient Details Update", 
"Laboratory", 
"Diagnostic Master", 
"Order Booking", 
"Order Booking", 
"Order Booking Search", 
"Cancel Order Booking", 
"Confidential Order Booking Request", 
"Pending For Sample Validation", 
"Pending For Sample Validation Search", 
"Pending For Sample Validation Details", 
"Pending For Result Entry", 
"Pending For Result Entry Search", 
"Pending For Result Entry Details", 
"Pending For Result Validation", 
"Pending For Result Validation Search", 
"Pending For Result Validation Details", 
"Result Delivery", 
"Result Delivery Search", 
"Result Delivery Details", 
"Result Printing", 
"Result Modification", 
"Result Modification Search", 
"Result Modification Details", 
"Radiology", 
"Diagnostic Master", 
"Order Booking", 
"Radiology Order Booking", 
"Radiology Cancel Order Booking", 
"Radiology Acceptance For Investigations", 
"Radiology Acceptance For Investigations Search", 
"Radiology Acceptance For Investigations Details", 
"Pending For Report Entry", 
"Radiology Pending For Report Entry Search", 
"Radiology Pending For Report Entry Details", 
"Pending For Report Validation", 
"Radiology Pending For Report Validation Search", 
"Radiology Pending For Report Validation Details", 
"Film Entry", 
"Report Delivery", 
"Radiology Report Delivery Search", 
"Radiology Report Delivery Details", 
"Result Printing", 
"Radiology Confidential Order Booking Request", 
"In Patient Department", 
"IPD Nursing Station", 
"IPD Clinical Setup", 
"IPD Nursing Entry", 
"IPD Clinical Chart", 
"IPD Intake/Output", 
"IPD Discharge Sum General", 
"IPD Discharge Sum O & G", 
"IPD Discharge Sum Paediatrice", 
"IPD Discharge Sum NABH", 
"IPD Ward Consumption", 
"IPD Food Fasting", 
"IPD Patient Issue", 
"IPD Department Indent", 
"IPD Patient Diagnosis", 
"IPD SILDIL", 
"IPD Patient Transfer", 
"IPD Patient Discharge", 
"IPD Daily Remarks", 
"IPD Patient Remarks", 
"IPD Order Booking", 
"IPD Order Status", 
"Operation Theatre", 
"PAC Clearance List", 
"OT Booking List", 
"OT List Change", 
"Post OP Notes Anaesthesia Search", 
"Post OP Notes Anaesthesia Details", 
"Post OP Notes Surgery Search", 
"Post OP Notes Surgery Details", 
"Specimen Dispatch Entry Search", 
"Specimen Dispatch Entry Details", 
"Human Body Parts Disposal Search", 
"Human Body Parts Disposal Details", 
"Surgery Enquiry", 
"Actual Surgery Perform", 
"Surgery Requesitions", 
"Blood Bank", 
"Blood Component Master", 
"Consent for Blood Transfusion Entry", 
"Blood Request Entry", 
"Pending For Blood Grouping & Cross Matching", 
"Blood Issue Entry", 
"Blood Donation Entry", 
"Update Blood Donation Entry", 
"Donor Blood Pending For Sample Screering", 
"Blood Reaction Form Entry", 
"Update Blood Reaction", 
"Investigation Pending For Transfusion Reaction", 
"Blood Test Entry", 
"Update Blood Test Entry", 
"Blood Component Separation", 
"Pending Blood Discard Entry", 
"Blood Stock Opening Balance Entry", 
"Pending for Sample Receipt Entry", 
"Pending Sample Validation", 
"Diet", 
"Patient Diet Change", 
"Daily Diet & Extra Requisition", 
"Extra Items Formula", 
"Menu Item Formula", 
"Indent Item Formula", 
"Internal Demand & Issue Voucher", 
"Breakfast Distribution", 
"MIS", 
"ED Returns", 
"Fatal Document Tracking", 
"FRW Requisition", 
"Birth Certificate", 
"Death Certificate", 
"Update Birth Certificate", 
"Update Death Certificate", 
"Annual Medical Examination", 
"Tender Process", 
"Tender Creation", 
"Invitation for Tender", 
"Tender Document", 
"Export Tender Data", 
"Import Tender Data", 
"Technical Bid", 
"Board Recommendations", 
"Tender PNC", 
"Tender LPO Note", 
"Tender Proposal", 
"Tender SO FOR L1", 
"Tender RE SO For Cancelled", 
"Re Tender Proposal", 
"Re Tender SO For L1", 
"Re Tender RE SO For Cancelled", 
"Prevuious Tender Items", 
"Stores Consumable/Expendable", 
"MMF Projections To DGAFMS", 
"Indent To Depot", 
"SOC Indent", 
"Store SOC Tracker", 
"Local Supply Order", 
"Store CRV", 
"LoanIn", 
"Issue CIV IAFF(Q) 429 ", 
"Loan Out", 
"Issue To Other Than Airforce Units", 
"Department Return", 
"Vendor Return", 
"AT/Supply Order Entry", 
"Opening Balance Entry", 
"Certificate of Stock Taking", 
"Defective Drugs Entry", 
"Issues To Other Units", 
"ACK", 
"MMF Department Approval", 
"CRV Ledger Action", 
"MMF Entry", 
"Non Expendable Stores ", 
"Non Expendable - LoanIn", 
"NonExpendable-CRV", 
"AMC Maintenance", 
"ME ScaleEquipment", 
"Indent to DGAFMS (SOC)", 
"Work Order", 
"AMC Repair", 
"SOC Tracker", 
"Issue CIVAFF(Q) 429", 
"Condemnation Entry", 
"Board of Survey", 
"Laundry", 
"Laundry Machine Master", 
"Linen Weight Master", 
"Machine Activity Entry", 
"Drivers Car Diary Entry", 
"Daily WorkLoad Entry", 
"CSSD", 
"Instrument Master", 
"Material Stock Entry", 
"Autoclave Request", 
"Autoclave Entry", 
"Material Master", 
"Autoclave Material Recipt", 
"Sterilize Recall", 
"Library", 
"Library Master", 
"Book Master", 
"Book Category Master", 
"Book Class Master", 
"Book Sub Class Master", 
"Vendor Master", 
"Publisher Master", 
"Supply Order Entry", 
"Update Supply Order Entry", 
"CRV Entry", 
"Update CRV Entry", 
"Journal Receipt Register", 
"Update Journal Receipt Entry", 
"Book/Journal Issue Entry", 
"Update Book/Journal Issue Entry", 
"Book/Journal Return Entry", 
"Update Book/Journal Return Entry", 
"Book Stock Taking Entry", 
"Update Book Stock Taking Entry", 
"HR", 
"Leave Maintenance", 
"Night Duty Entry", 
"Guard Duty Entry", 
"Ward Duty Entry", 
"Orderly SGT Duty Entry", 
"Range Firing Duty Entry", 
"Duty Display For Service Personnel", 
"Duty Exemption Entry", 
"Detailing Of Daily Routine, Scott & Sick Transfer Duty Entry", 
"Update Arrival Service Personnel Details", 
"Leave Application Pending For Recommenation", 
"Masters", 
"Laboratory Related", 
"Sample Container Master", 
"Investigation UOM", 
"Collection Center", 
"Organism Group", 
"Organism", 
"Sensitivity", 
"Parameter Master", 
"Organism Group Detail", 
"Organism Detail", 
"Biopsy", 
"Sample", 
"Blood Bank", 
"Blood Bank Status", 
"Blood Donation", 
"Blood Group", 
"Registration Related", 
"Document", 
"Admission Type", 
"Administrative Sex", 
"Title", 
"Marital Status", 
"Occupation", 
"Caste", 
"Religion", 
"Relation", 
"Reference", 
"Disposal", 
"OT Masters", 
"OT Entry", 
"OT Distribution", 
"Anesthesia", 
"OPD Master", 
"OPD Holiday", 
"OPD Treatment Template", 
"OPD Instruction Treatment", 
"OPD Template Investigation", 
"Opd Vaccinating", 
"OPD Equipment", 
"OPD Frequency", 
"OPD Physiotherapy Treatment", 
"Diet", 
"Diet", 
"Diet Menu Item", 
"Diet Combination", 
"Diet Indent Item", 
"Diet Type", 
"Diet Items", 
"General Master", 
"Country", 
"Currency", 
"State", 
"District", 
"Block", 
"Post Code", 
"System Related", 
"Department Type", 
"Transaction Type", 
"Frequency", 
"Department Master", 
"Personnel", 
"Rank Category", 
"Employee Status", 
"Employee Dependent", 
"Referral Doctor", 
"Employee", 
"Rank", 
"Formation", 
"Unit", 
"Trade", 
"Record Office Address", 
"HR Related", 
"Speciality Master", 
"Medical Course Master", 
"Leave Type Master", 
"Duty Time Master", 
"Duty Master", "
"Establishment Master for Medical Assistant", 
"Hospital Related", 
"Nursing Care", 
"Case Type", 
"Cause Of Death", 
"Main Type", 
"Sub Type", 
"Cost Centre", 
"Complaint Code", 
"Complications", 
"Authorizer", 
"Bed Master", 
"Bed Status Master", 
"Test Master", 
"Room Master", 
"ICD Cause Group", 
"ICD Sub Category", 
"ICD Main Category", 
"ICD Master", 
"Service Type", 
"Service Status", 
"In-patient Related", 
"Disposed To", 
"Care Type", 
"Discharge Status", 
"Discharge Items", 
"Injury Nature", 
"Bed Status", 
"Baby Status", 
"Delivery Type", 
"Marriage Accomodation", 
"Pool Category Master", 
"Pool Master", 
"Location Master", 
"SMQ Master", 
"Car Garage Master", 
"Stores", 
"PVMS/NIV", 
"PVMS/NIV Section", 
"PVMS/NIV Sub Section", 
"PVMS/NIV Groups", 
"Financial", 
"Accounting Unit(A/U) Conversion", 
"Item Unit", 
"Item Type", 
"Budget Master", 
"AirForce Unit Depot", 
"ME Scale", 
"Supply Order Delivery/Payment Terms", 
"Manufacturer", 
"Supplier Type", 
"Vendor Master", 
"Pharma Index", 
"Security", 
"Module Management ", 
"Hospital Master", 
"Application Group", 
"Employee Group", 
"Add Form/Reports", 
"Edit Form/Reports", 
"User Creation", 
"User Management", 
"User Management Details", 
"User Group Hospital", 
"User Hospital Maintenace", 
"User Department", 
"Button Details", 
"Remove Button Rights", 
"View/Remove User Rights", 
"Change Order", 
"Change word/Department", 
"Change Pasword", 
"Assign Button Rights to Employee Groups", 
"Assign Application Rights to User", 
"Assign Module Rights to Employee Groups", 
"Agenda Points", 
"Agenda Points For Work Services", 
"Agenda Point Search", 
"Priority for Agenda Points", 
"MOM Details Against Agenda", 
"HR Orderly Room", 
"Leave Details", 
"Leave Application", 
"Leave Application Update", 
"Leave Application Pending For Approval", 
"Leave Restriction", 
"Employee Arrival Form", 
"Employee Update Form", 
"Clearence From", 
"Medical Board Proceedings", 
"Type Of Entry Master", 
"Medical Board Proceedings Search", 
"Medical Examination Report On Entry", 
"Candidate Found Unfit By Board", 
"Certificate By The Candidate", 
"Result OF Appeal Medical Board Entry", 
"Complaint Monitoring System", 
"Complaint Type Master", 
"Complaints Register", 
"Work Completion Details", 
"Work Not Completed With In 3 Days", 
"Medical Claim", 
"Sanction Authority Master", 
"Request for Special Investigation Entry", 
"Update Special Investigation Entry", 
"Contingent Bill For Reimbursement For Medical", 
"Update Contingent Bill For Reimbursement For Medical", 
"Covering Letters to Unit", 
"General Claim Covering letter Amount", 
"General Claim Tracking", 
"Cardiac Claim for Advance, Undertaking & Willingness", 
"Update Cardiac claim for Advance, Undertaking & Willingness", 
"Cardiac Claim Contingent Bill for Reimbursement", 
"Update Cardiac Claim Contingent Bill for Reimbursement", 
"Contingent Bill Movement Entry", 
"Cardiac Claim Tracking", 
"Pension", 
"Designation Master", 
"Group Master", 
"Commutation Weightage Master", 
"Personal Entry Details", 
"Update Personal Entry Details", 
"Calculation Sheet", 
"Update Calculation Sheet", 
"Data Sheet", 
"Update Data Sheet", 
"Form 7 Entry", 
"Update Form 7 Entry", 
"Form 8 Entry", 
"Update Form 8 Entry", 
"Form 356 Retirement Entry", 
"Update Form 356 Retirement Entry", 
"Work Services", 
"Work Category", 
"Work Type", 
"Minor Work Proposal", 
"Minor Work Proposal Cancellation ", 
"Minor Work Details", 
"Minor Work Details Approval", 
"Minor Work Detail", 
"Minor Work Detail Search", 
"Minor Work Detail Search For Completion Work", 
"Minor Work User Comments", 
"Major Work Details", 
"Major Work Detail", 
"Major Work Detail Search/Completion", 
"Marriage Accommodation", 
"Pool Category", 
"Pool Master", 
"Location Master", 
"SMQ Master", 
"Car Garage Master", 
"Accommodation Registration for Airmen", 
"Allotment of married Accomodation for Airmen", 
"Cancellation of Allotment Order for Airmen", 
"SMQ Vacation for Airmen", 
"Allotment/Vacation Of SMQ for Airmen", 
"Occupancy / Vacation Return for Airmen", 
"Accomodation registration for Officer", 
"Issue of Willingness Certificate", 
"Allotment Of SMQs/Garages Officers", 
"Cancellation of Allotment Order for Officer", 
"SMQ Vacation for Officer", 
"Relegation Process", 
"Allotment/Vacation Of SMQ for Officer", 
"Occupancy / Vacation Return for Officer", 
"Non Availability Certificate (NAC)", 
