/*************************************************************************

Fly Help Web Help Index Library 1.0
Copyright (c) 2001-2005 Fly Sky Software,Inc. 
http://www.flyskysoft.com

Tested with: Internet Explorer 5, Opera 6, Mozilla 1.2, NN6

ATTENTION! You can use this library only with web help system 
generated by Fly Help software.  
               
**************************************************************************/
String.prototype.trim = function() {
    return this.replace(/^\s*/, "").replace(/\s*$/, "");
}

function Startup() {
    for (var i = 0; i < IndexItems.length; i++) {
        var e = document.createElement("OPTION");
        e.text = IndexItems[i][0];
        e.value = i;
        document.forms[0].indexlist[document.forms[0].indexlist.length] = e;
    }
}
var oldS = "";
function SelectMatch(str) {
    webhelptop.whtopframe.indexquery = str;
    var s = str.toUpperCase();
    if ((s == "") || (s == oldS))
        return false;
    oldS = s;
    var re = new RegExp("^" + s);
    var h = Math.floor(document.forms[0].indexlist.length / 100);
    var start = h * 100;
    var end = document.forms[0].indexlist.length - 1;
    if (h > 0)
        for (var i = 0; i <= h; i++)
        if (s < document.forms[0].indexlist[i * 100].text.toUpperCase()) {
        start = (i - 1) * 100;
        if (start < 0)
            start = 0;
        end = i * 100;
        end = document.forms[0].indexlist.length - 1;
        break;
    }
    for (var i = 0; i <= end; i++) {

        try {
            if (re.test(document.forms[0].indexlist[i].text.toUpperCase().trim())) {

                document.forms[0].indexlist[i].selected = true;
                i = end + 2;
                return false;
            }
        } catch (Err) { }
    }

    return true;
}
function ShowMatch() {
    var str = IndexItems[document.forms[0].indexlist[document.forms[0].indexlist.selectedIndex].value][1];
    if (str.substr(0, 3) == "@@@") {
        str = str.substr(3); oldS = "";
        SelectMatch(str);
        return true;
    };
    if (document.forms[0].indexlist.selectedIndex >= 0) {
        open(str, "content");
        webhelptop.whtopframe.pageid = str;
        return true;
    }
    else
        return false;
}
